stages:
  process_data:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw/train.csv
      - data/raw/test.csv
      - src/data_preprocessing.py
    outs:
      - data/processed/train_processed.csv
      - data/processed/val_processed.csv
      - data/processed/test_processed.csv
  
  train_data:
    cmd: python src/train.py
    deps:
      - data/processed/train_processed.csv
      - data/processed/val_processed.csv
      - src/train.py
    outs:
      - models/latest_model