channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=25.0.1
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==24.2
  - psutil==7.0.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
